-- Tradeskills_HousingDyes.lua
-- Generated by bin/catdb_tradeskill_emit.py from playable recipes (12.1.0.69404).
-- Do not edit by hand. scanCache is not shipped.
local _, ns = ...

local data = {
    pid = 2984,
    name = "HousingDyes",
    icon = 7449434,
    r = {},
}
local r = data.r
r[1264469] = {
    id = 1264469,
    item = 259053,
    icon = 7449469,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264712] = {
    id = 1264712,
    item = 259109,
    icon = 7449418,
    cat = 2679,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1264713] = {
    id = 1264713,
    item = 259120,
    icon = 7449413,
    cat = 2678,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {260947, 1, 1},
    },
}
r[1264715] = {
    id = 1264715,
    item = 259116,
    icon = 7449441,
    cat = 2677,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262625, 1, 1},
    },
}
r[1264717] = {
    id = 1264717,
    item = 259136,
    icon = 7449468,
    cat = 2675,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262628, 1, 1},
    },
}
r[1264719] = {
    id = 1264719,
    item = 259115,
    icon = 7449410,
    cat = 2676,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262643, 1, 1},
    },
}
r[1264720] = {
    id = 1264720,
    item = 259114,
    icon = 7449444,
    cat = 2674,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262647, 1, 1},
    },
}
r[1264721] = {
    id = 1264721,
    item = 258838,
    icon = 7449430,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1264722] = {
    id = 1264722,
    item = 259118,
    icon = 7449425,
    cat = 2672,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262656, 1, 1},
    },
}
r[1264725] = {
    id = 1264725,
    item = 259127,
    icon = 7449427,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1264760] = {
    id = 1264760,
    item = 258838,
    icon = 7449430,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1264885] = {
    id = 1264885,
    item = 259121,
    icon = 7449452,
    cat = 2679,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1264886] = {
    id = 1264886,
    item = 259123,
    icon = 7449460,
    cat = 2679,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1264889] = {
    id = 1264889,
    item = 259153,
    icon = 7449421,
    cat = 2676,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262643, 1, 1},
    },
}
r[1264891] = {
    id = 1264891,
    item = 259129,
    icon = 7449471,
    cat = 2676,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262643, 1, 1},
    },
}
r[1264894] = {
    id = 1264894,
    item = 259135,
    icon = 7449447,
    cat = 2676,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262643, 1, 1},
    },
}
r[1264895] = {
    id = 1264895,
    item = 259146,
    icon = 7449449,
    cat = 2676,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262643, 1, 1},
    },
}
r[1264912] = {
    id = 1264912,
    item = 259078,
    icon = 7449412,
    cat = 2678,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {260947, 1, 1},
    },
}
r[1264913] = {
    id = 1264913,
    item = 259099,
    icon = 7449435,
    cat = 2678,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {260947, 1, 1},
    },
}
r[1264914] = {
    id = 1264914,
    item = 259149,
    icon = 7449434,
    cat = 2678,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {260947, 1, 1},
    },
}
r[1264916] = {
    id = 1264916,
    item = 259096,
    icon = 7449446,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264921] = {
    id = 1264921,
    item = 259098,
    icon = 7449419,
    cat = 2679,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1264924] = {
    id = 1264924,
    item = 259101,
    icon = 7449453,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264926] = {
    id = 1264926,
    item = 259102,
    icon = 7449445,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1264928] = {
    id = 1264928,
    item = 259103,
    icon = 7449433,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264936] = {
    id = 1264936,
    item = 259112,
    icon = 7449417,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264938] = {
    id = 1264938,
    item = 259122,
    icon = 7449423,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264940] = {
    id = 1264940,
    item = 259132,
    icon = 7449442,
    cat = 2672,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262656, 1, 1},
    },
}
r[1264942] = {
    id = 1264942,
    item = 259141,
    icon = 7449467,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264944] = {
    id = 1264944,
    item = 259142,
    icon = 7449456,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1264945] = {
    id = 1264945,
    item = 259145,
    icon = 7449464,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1264950] = {
    id = 1264950,
    item = 259150,
    icon = 7449424,
    cat = 2674,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262647, 1, 1},
    },
}
r[1264952] = {
    id = 1264952,
    item = 259105,
    icon = 7449416,
    cat = 2672,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262656, 1, 1},
    },
}
r[1264954] = {
    id = 1264954,
    item = 259108,
    icon = 7449415,
    cat = 2672,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262656, 1, 1},
    },
}
r[1264955] = {
    id = 1264955,
    item = 259128,
    icon = 7449440,
    cat = 2680,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1265077] = {
    id = 1265077,
    item = 259111,
    icon = 7449439,
    cat = 2679,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1265078] = {
    id = 1265078,
    item = 259124,
    icon = 7449459,
    cat = 2674,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262647, 1, 1},
    },
}
r[1265079] = {
    id = 1265079,
    item = 259125,
    icon = 7449465,
    cat = 2675,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262628, 1, 1},
    },
}
r[1265080] = {
    id = 1265080,
    item = 259133,
    icon = 7449422,
    cat = 2674,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262647, 1, 1},
    },
}
r[1265081] = {
    id = 1265081,
    item = 259143,
    icon = 7449431,
    cat = 2674,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262647, 1, 1},
    },
}
r[1265082] = {
    id = 1265082,
    item = 259147,
    icon = 7449432,
    cat = 2674,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262647, 1, 1},
    },
}
r[1265084] = {
    id = 1265084,
    item = 259119,
    icon = 7449450,
    cat = 2677,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262625, 1, 1},
    },
}
r[1265085] = {
    id = 1265085,
    item = 259126,
    icon = 7449466,
    cat = 2677,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262625, 1, 1},
    },
}
r[1265086] = {
    id = 1265086,
    item = 259130,
    icon = 7449451,
    cat = 2677,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262625, 1, 1},
    },
}
r[1265087] = {
    id = 1265087,
    item = 259131,
    icon = 7449411,
    cat = 2677,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262625, 1, 1},
    },
}
r[1265088] = {
    id = 1265088,
    item = 259140,
    icon = 7449448,
    cat = 2677,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262625, 1, 1},
    },
}
r[1265089] = {
    id = 1265089,
    item = 259144,
    icon = 7449428,
    cat = 2677,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262625, 1, 1},
    },
}
r[1265091] = {
    id = 1265091,
    item = 259113,
    icon = 7449438,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1265092] = {
    id = 1265092,
    item = 259139,
    icon = 7449429,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1265093] = {
    id = 1265093,
    item = 259151,
    icon = 7449420,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {785, 10, 1},
    },
}
r[1265094] = {
    id = 1265094,
    item = 259152,
    icon = 7449436,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1265097] = {
    id = 1265097,
    item = 259154,
    icon = 7449455,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1265098] = {
    id = 1265098,
    item = 259134,
    icon = 7449426,
    cat = 2674,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262647, 1, 1},
    },
}
r[1265099] = {
    id = 1265099,
    item = 259104,
    icon = 7449461,
    cat = 2679,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1265100] = {
    id = 1265100,
    item = 259110,
    icon = 7449443,
    cat = 2675,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262628, 1, 1},
    },
}
r[1265101] = {
    id = 1265101,
    item = 259148,
    icon = 7449463,
    cat = 2675,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262628, 1, 1},
    },
}
r[1265102] = {
    id = 1265102,
    item = 259097,
    icon = 7449454,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265103] = {
    id = 1265103,
    item = 259100,
    icon = 7449437,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265104] = {
    id = 1265104,
    item = 259106,
    icon = 7449470,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265105] = {
    id = 1265105,
    item = 259107,
    icon = 7449414,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265106] = {
    id = 1265106,
    item = 259117,
    icon = 7449457,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265107] = {
    id = 1265107,
    item = 259137,
    icon = 7449462,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265109] = {
    id = 1265109,
    item = 259138,
    icon = 7449458,
    cat = 2673,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265111] = {
    id = 1265111,
    item = 259112,
    icon = 7449417,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1265112] = {
    id = 1265112,
    item = 259109,
    icon = 7449418,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1265113] = {
    id = 1265113,
    item = 259111,
    icon = 7449439,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1265114] = {
    id = 1265114,
    item = 259105,
    icon = 7449416,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262656, 1, 1},
    },
}
r[1265115] = {
    id = 1265115,
    item = 259108,
    icon = 7449415,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262656, 1, 1},
    },
}
r[1265116] = {
    id = 1265116,
    item = 259104,
    icon = 7449461,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1265117] = {
    id = 1265117,
    item = 259110,
    icon = 7449443,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262628, 1, 1},
    },
}
r[1265119] = {
    id = 1265119,
    item = 259106,
    icon = 7449470,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265120] = {
    id = 1265120,
    item = 259107,
    icon = 7449414,
    cat = 2681,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1265121] = {
    id = 1265121,
    item = 259139,
    icon = 7449429,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1265122] = {
    id = 1265122,
    item = 259151,
    icon = 7449420,
    cat = 2671,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1277200] = {
    id = 1277200,
    item = 259097,
    icon = 7449454,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1277201] = {
    id = 1277201,
    item = 259100,
    icon = 7449437,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262648, 1, 1},
    },
}
r[1277204] = {
    id = 1277204,
    item = 259099,
    icon = 7449435,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {260947, 1, 1},
    },
}
r[1277205] = {
    id = 1277205,
    item = 259078,
    icon = 7449412,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {260947, 1, 1},
    },
}
r[1277206] = {
    id = 1277206,
    item = 259102,
    icon = 7449445,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262655, 1, 1},
    },
}
r[1277207] = {
    id = 1277207,
    item = 259053,
    icon = 7449469,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1277208] = {
    id = 1277208,
    item = 259101,
    icon = 7449453,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1277209] = {
    id = 1277209,
    item = 259096,
    icon = 7449446,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1277210] = {
    id = 1277210,
    item = 259103,
    icon = 7449433,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262642, 1, 1},
    },
}
r[1277215] = {
    id = 1277215,
    item = 259098,
    icon = 7449419,
    cat = 2727,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
    rg = {
        {262639, 1, 1},
    },
}
r[1306629] = {
    id = 1306629,
    icon = 7449441,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306642] = {
    id = 1306642,
    icon = 7449452,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306796] = {
    id = 1306796,
    icon = 7449410,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306797] = {
    id = 1306797,
    icon = 7449433,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306799] = {
    id = 1306799,
    icon = 7449444,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306801] = {
    id = 1306801,
    icon = 7449425,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306802] = {
    id = 1306802,
    icon = 7449438,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306803] = {
    id = 1306803,
    icon = 7449413,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
r[1306804] = {
    id = 1306804,
    icon = 7449457,
    cat = 2670,
    pid = 2984,
    prof = "HousingDyes",
    exp = "Midnight",
    min = 1,
}
ns:RegisterProfessionData(data)
