-- Tradeskills_Fishing.lua
-- Generated by bin/catdb_tradeskill_emit.py from playable recipes (12.1.0.69404).
-- Do not edit by hand. scanCache is not shipped.
local _, ns = ...

local data = {
    pid = 356,
    name = "Fishing",
    icon = 136245,
    r = {},
}
local r = data.r
r[7620] = {
    id = 7620,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    next = 7731,
    learn = "trainer",
    npc = 23896,
}
r[7731] = {
    id = 7731,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 7620,
    next = 7732,
}
r[7732] = {
    id = 7732,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 7731,
    next = 18248,
}
r[7738] = {
    id = 7738,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    lo = 1,
    hi = 1,
    learn = "trainer",
}
r[18248] = {
    id = 18248,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 7732,
    next = 33095,
}
r[33095] = {
    id = 33095,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 18248,
    next = 51294,
}
r[43308] = {
    id = 43308,
    icon = 133888,
    cat = 1700,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    lo = 1,
    hi = 1,
    taught = 34109,
}
r[51294] = {
    id = 51294,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 33095,
    next = 88868,
}
r[88868] = {
    id = 88868,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 51294,
    next = 110410,
}
r[110410] = {
    id = 110410,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 88868,
    next = 158743,
}
r[131474] = {
    id = 131474,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
}
r[131476] = {
    id = 131476,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
}
r[131490] = {
    id = 131490,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
}
r[158743] = {
    id = 158743,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    prev = 110410,
}
r[271656] = {
    id = 271656,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[271658] = {
    id = 271658,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[271660] = {
    id = 271660,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[271662] = {
    id = 271662,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[271664] = {
    id = 271664,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[271672] = {
    id = 271672,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[271675] = {
    id = 271675,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[271677] = {
    id = 271677,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 138026,
}
r[271990] = {
    id = 271990,
    icon = 3615516,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
}
r[272011] = {
    id = 272011,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
}
r[310675] = {
    id = 310675,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 23896,
}
r[366253] = {
    id = 366253,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 216258,
}
r[423336] = {
    id = 423336,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 218751,
}
r[471008] = {
    id = 471008,
    icon = 4620674,
    pid = 356,
    prof = "Fishing",
    exp = "Classic",
    min = 1,
    learn = "trainer",
    npc = 253468,
}
r[393059] = {
    id = 393059,
    icon = 4554372,
    cat = 1806,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393060] = {
    id = 393060,
    icon = 4539687,
    cat = 1807,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393061] = {
    id = 393061,
    icon = 4539689,
    cat = 1807,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393062] = {
    id = 393062,
    icon = 4554371,
    cat = 1806,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393063] = {
    id = 393063,
    icon = 1387373,
    cat = 1809,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393064] = {
    id = 393064,
    icon = 4554376,
    cat = 1809,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393065] = {
    id = 393065,
    icon = 4638725,
    cat = 1809,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393066] = {
    id = 393066,
    icon = 4554377,
    cat = 1808,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393067] = {
    id = 393067,
    icon = 4554379,
    cat = 1808,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[393068] = {
    id = 393068,
    icon = 630618,
    cat = 1808,
    pid = 356,
    prof = "Fishing",
    exp = "Dragonflight",
    min = 1,
    lo = 10,
    hi = 50,
    learn = "trainer",
}
r[444785] = {
    id = 444785,
    icon = 133908,
    cat = 2068,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444786] = {
    id = 444786,
    icon = 970826,
    cat = 2068,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444787] = {
    id = 444787,
    icon = 1387364,
    cat = 2068,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444788] = {
    id = 444788,
    icon = 630618,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444789] = {
    id = 444789,
    icon = 2921025,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444790] = {
    id = 444790,
    icon = 133929,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444791] = {
    id = 444791,
    icon = 237324,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444792] = {
    id = 444792,
    icon = 4539687,
    cat = 2068,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444793] = {
    id = 444793,
    icon = 630619,
    cat = 2068,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444794] = {
    id = 444794,
    icon = 348529,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444795] = {
    id = 444795,
    icon = 349504,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444796] = {
    id = 444796,
    icon = 632356,
    cat = 2070,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444797] = {
    id = 444797,
    icon = 1339352,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444798] = {
    id = 444798,
    icon = 970827,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444799] = {
    id = 444799,
    icon = 4554374,
    cat = 2070,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 1,
    hi = 1,
}
r[444800] = {
    id = 444800,
    icon = 4539689,
    cat = 2070,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444801] = {
    id = 444801,
    icon = 347920,
    cat = 2070,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444802] = {
    id = 444802,
    icon = 631038,
    cat = 2070,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[444803] = {
    id = 444803,
    icon = 2564610,
    cat = 2070,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
}
r[454441] = {
    id = 454441,
    icon = 643874,
    cat = 2120,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    learn = "trainer",
}
r[454442] = {
    id = 454442,
    icon = 236574,
    cat = 2120,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 25,
    learn = "trainer",
}
r[454443] = {
    id = 454443,
    icon = 350870,
    cat = 2069,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
}
r[456150] = {
    id = 456150,
    icon = 2066208,
    cat = 2122,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    learn = "trainer",
}
r[456152] = {
    id = 456152,
    icon = 3622220,
    cat = 2122,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
}
r[456154] = {
    id = 456154,
    icon = 3622226,
    cat = 2122,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
}
r[456180] = {
    id = 456180,
    icon = 5746561,
    cat = 2123,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 150,
    learn = "trainer",
}
r[456588] = {
    id = 456588,
    icon = 5770811,
    cat = 2123,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    learn = "trainer",
}
r[456589] = {
    id = 456589,
    icon = 5770812,
    cat = 2123,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 75,
    learn = "trainer",
}
r[456590] = {
    id = 456590,
    icon = 5770810,
    cat = 2123,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 150,
    learn = "trainer",
}
r[456591] = {
    id = 456591,
    icon = 5770809,
    cat = 2123,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 225,
    learn = "trainer",
}
r[471359] = {
    id = 471359,
    icon = 533422,
    cat = 2070,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 1,
    lo = 10,
    hi = 50,
}
r[471365] = {
    id = 471365,
    icon = 463874,
    cat = 2123,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 225,
    learn = "trainer",
}
r[471368] = {
    id = 471368,
    icon = 632354,
    cat = 2123,
    pid = 356,
    prof = "Fishing",
    exp = "TheWarWithin",
    min = 225,
    learn = "trainer",
}
r[1225245] = {
    id = 1225245,
    icon = 133927,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225266] = {
    id = 1225266,
    icon = 4554378,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225267] = {
    id = 1225267,
    icon = 7549009,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225268] = {
    id = 1225268,
    icon = 237311,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225269] = {
    id = 1225269,
    icon = 2027868,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225270] = {
    id = 1225270,
    icon = 7549006,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225271] = {
    id = 1225271,
    icon = 237323,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225272] = {
    id = 1225272,
    icon = 347920,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225273] = {
    id = 1225273,
    icon = 5869497,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225274] = {
    id = 1225274,
    icon = 4554382,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225275] = {
    id = 1225275,
    icon = 7549000,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225276] = {
    id = 1225276,
    icon = 133924,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225277] = {
    id = 1225277,
    icon = 133922,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225278] = {
    id = 1225278,
    icon = 237304,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225279] = {
    id = 1225279,
    icon = 237320,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225280] = {
    id = 1225280,
    icon = 237315,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225281] = {
    id = 1225281,
    icon = 7549001,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225282] = {
    id = 1225282,
    icon = 5976715,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225283] = {
    id = 1225283,
    icon = 2057313,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225284] = {
    id = 1225284,
    icon = 3535747,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1225322] = {
    id = 1225322,
    icon = 236762,
    cat = 2198,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    learn = "trainer",
}
r[1225335] = {
    id = 1225335,
    icon = 7578705,
    cat = 2198,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 75,
    learn = "trainer",
}
r[1225336] = {
    id = 1225336,
    icon = 7507880,
    cat = 2198,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 225,
    learn = "trainer",
}
r[1225337] = {
    id = 1225337,
    icon = 7385004,
    cat = 2198,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 150,
    learn = "trainer",
}
r[1225340] = {
    id = 1225340,
    icon = 643874,
    cat = 2199,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    learn = "trainer",
}
r[1226157] = {
    id = 1226157,
    item = 241145,
    icon = 970850,
    cat = 2208,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    lo = 1,
    hi = 1,
    rg = {
        {238365, 5, 1},
    },
    taught = 244816,
    learn = "item",
}
r[1226159] = {
    id = 1226159,
    item = 241148,
    icon = 2101983,
    cat = 2208,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    rg = {
        {238377, 2, 1},
    },
    taught = 244791,
    learn = "item",
}
r[1226161] = {
    id = 1226161,
    item = 241149,
    icon = 4554365,
    cat = 2208,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    rg = {
        {238380, 5, 1},
    },
    taught = 244815,
    learn = "item",
}
r[1231090] = {
    id = 1231090,
    icon = 970851,
    cat = 2208,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    taught = 244818,
}
r[1235486] = {
    id = 1235486,
    item = 241147,
    icon = 970847,
    cat = 2208,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    rg = {
        {238382, 5, 1},
    },
    taught = 244817,
    learn = "item",
}
r[1265717] = {
    id = 1265717,
    icon = 4620674,
    cat = 2705,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    lo = 1,
    hi = 1,
    learn = "trainer",
}
r[1265725] = {
    id = 1265725,
    icon = 970843,
    cat = 2705,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    lo = 1,
    hi = 1,
    learn = "trainer",
}
r[1295404] = {
    id = 1295404,
    icon = 7548999,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295405] = {
    id = 1295405,
    icon = 7816879,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295406] = {
    id = 1295406,
    icon = 7816885,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295407] = {
    id = 1295407,
    icon = 970820,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295408] = {
    id = 1295408,
    icon = 970814,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295409] = {
    id = 1295409,
    icon = 4554382,
    cat = 2197,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295410] = {
    id = 1295410,
    icon = 970823,
    cat = 2233,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295411] = {
    id = 1295411,
    icon = 7816875,
    cat = 2234,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295420] = {
    id = 1295420,
    icon = 7549804,
    cat = 2198,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 75,
    learn = "trainer",
}
r[1295421] = {
    id = 1295421,
    icon = 7549804,
    cat = 2198,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295422] = {
    id = 1295422,
    icon = 7578705,
    cat = 2198,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1295922] = {
    id = 1295922,
    item = 275013,
    icon = 2446022,
    cat = 2208,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    rg = {
        {238377, 3, 1},
        {274592, 30, 1},
        {274590, 6, 1},
        {274777, 2, 1},
    },
    taught = 275012,
}
r[1302819] = {
    id = 1302819,
    item = 277821,
    icon = 970850,
    cat = 2208,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    rg = {
        {274588, 5, 1},
    },
    taught = 277820,
}
r[1303630] = {
    id = 1303630,
    icon = 2061891,
    cat = 2199,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
    learn = "trainer",
}
r[1305972] = {
    id = 1305972,
    icon = 4554382,
    cat = 2756,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1305973] = {
    id = 1305973,
    icon = 133729,
    cat = 2756,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1305975] = {
    id = 1305975,
    icon = 4554382,
    cat = 2756,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1305976] = {
    id = 1305976,
    icon = 3535750,
    cat = 2756,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1305978] = {
    id = 1305978,
    icon = 630789,
    cat = 2756,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
r[1305979] = {
    id = 1305979,
    icon = 350867,
    cat = 2756,
    pid = 356,
    prof = "Fishing",
    exp = "Midnight",
    min = 1,
}
ns:RegisterProfessionData(data)
