-- OneWoW Addon File (GENERATED - do not edit manually)
-- OneWoW/Services/PredicateEngine/season-bonus-lists.lua
-- Generated by bin/season_bonus_list_ids.py from .warehouse/Sources
-- Do not edit by hand; re-run: python bin/season_bonus_list_ids.py generate
local _, ns = ...

-- [expansionID][seasonOrdinal][bonusListID] = true
-- Sequence 1-8 PvE track lists only (excludes crafted sequence 9+).
ns.SeasonTrackBonusListIDs = {
    [11] = { -- Midnight
        [1] = {
            [12704]=true, [12762]=true, [12763]=true, [12764]=true, [12765]=true, [12766]=true, [12767]=true, [12768]=true, [12769]=true, [12770]=true,
            [12771]=true, [12772]=true, [12773]=true, [12774]=true, [12775]=true, [12776]=true, [12777]=true, [12778]=true, [12779]=true, [12780]=true,
            [12781]=true, [12782]=true, [12783]=true, [12784]=true, [12785]=true, [12786]=true, [12787]=true, [12788]=true, [12789]=true, [12790]=true,
            [12791]=true, [12792]=true, [12793]=true, [12794]=true, [12795]=true, [12796]=true, [12797]=true, [12798]=true, [12799]=true, [12800]=true,
            [12801]=true, [12802]=true, [12803]=true, [12804]=true, [12805]=true, [12806]=true, [12807]=true, [12808]=true,
        },
        [2] = {
            [12817]=true, [12818]=true, [12819]=true, [12820]=true, [12821]=true, [12822]=true, [12823]=true, [12824]=true, [12825]=true, [12826]=true,
            [12827]=true, [12828]=true, [12829]=true, [12830]=true, [12831]=true, [12832]=true, [12833]=true, [12834]=true, [12835]=true, [12836]=true,
            [12837]=true, [12838]=true, [12839]=true, [12840]=true, [12841]=true, [12842]=true, [12843]=true, [12844]=true, [12845]=true, [12846]=true,
            [12847]=true, [12848]=true, [12849]=true, [12850]=true, [12851]=true, [12852]=true, [12853]=true, [12854]=true, [12855]=true, [12856]=true,
        },
    },
}
