-- OneWoW_CatalogData_Quests_Archive main file.
-- Classic through Dragonflight shards register through Core/QuestDBLoader.lua;
-- Core.lua imports them into OneWoW_CatalogData_Quests_API. This unit exposes no globals.
